---
- name: Import interface name from .env.dev
  set_fact:
    new_interface_name: "{{ lookup('ini', 'HOST_INTERFACE type=properties file=' + env_file_path) }}"

- name: Import static IP from .env.dev
  set_fact:
    static_ip: "{{ lookup('ini', 'STATIC_IP type=properties file=' + env_file_path) }}"

  # Task 1: Configure Netplan for interface renaming and static IP
  - name: Configure Netplan for renaming and static IP
    copy:
      dest: /etc/netplan/01-network-manager-all.yaml
      content: |
        # Let NetworkManager manage all devices on this system
        network:
          version: 2
          renderer: NetworkManager
          ethernets:
            {{ new_interface_name }}:
              match:
                macaddress: "{{ mac_address }}"
              set-name: "{{ new_interface_name }}"
              dhcp4: no
              addresses:
                - "{{ static_ip }}/24"
      mode: "0644"
    become: yes
  
  # Task 2: Apply Netplan configuration
  - name: Apply Netplan configuration
    shell: netplan apply
    become: yes
  