# URLs for BSP and Rootfs
bsp_url: "https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/release/jetson_linux_r35.4.1_aarch64.tbz2"
rootfs_url: "https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/release/tegra_linux_sample-root-filesystem_r35.4.1_aarch64.tbz2"
bsp_file_name : "Jetson_Linux_R35.4.1_aarch64.tbz2"
rootfs_file_name: "Tegra_Linux_Sample-Root-Filesystem_R35.4.1_aarch64.tbz2"