---

  #-------------------------------------------
  # LXD and Python dependencies setup
  #-------------------------------------------
  - name: Ensure LXD is installed
    shell: snap install lxd --channel=latest/stable

  - name: Initialize LXD with minimal configuration
    shell: lxd init --minimal

  - name: Add local user to lxd group
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: lxd
      append: yes

  - name: Install Python packages using apt
    apt:
      name:
        - python3-fastapi
        - python3-pandas
        - python3-pylxd
        - python3-uvicorn
        - python3-redis
        - python3-netmiko
        - bzip2
        - python-dotenv
      state: present

  - name: Install remaining Python dependency with pip
    command: python3 -m pip install --break-system-packages ansible-pylibssh

  - name: Install jq using apt
    apt:
      name: jq
      state: present


  #-------------------------------------------
  # Additional dependencies and configuration
  #-------------------------------------------
  - name: Add universe repository
    apt_repository:
      repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
      state: present

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install qemu-user-static
    apt:
      name: qemu-user-static
      state: present



  - name: Install additional dependencies for user creation
    apt:
      name:
        - lz4
        - libxml2-utils
      state: present


  - name: Configure Jetson JP3541 system
    import_tasks: jetson_jp3541.yml
    vars_files:
      - "../vars/jetson_jp3541.yml"

  - name: Configure Jetson jp3274system
    import_tasks: jetson_jp3274.yml
    vars_files:
      - "../vars/jetson_jp3274.yml"



  #-------------------------------------------
  # Initialize active_users.json
  #-------------------------------------------
  - name: Initialize active_users.json with empty list
    copy:
      content: "[]"
      dest: "{{ system_manager_base_path }}/config/active_users.json"
      owner: nobody
      group: nogroup
      mode: '0666'
