version: '3'
services:
 dhcpd:
     build: .
     restart: unless-stopped
     networks:
         internal_network:
             ipv4_address: 192.168.0.2
     volumes:
         - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
networks:
 internal_network:
     external:
         name: macvlan0

